FROM python:3.11-slim
WORKDIR /app
COPY online_judge_backend/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt
COPY online_judge_backend ./online_judge_backend
CMD ["uvicorn", "online_judge_backend.app.main:app", "--host", "0.0.0.0", "--port", "8000"]
